### ISSUE TITLE
Quest cog building crashes every time.

### ISSUE THREAD

**Issue by NathanX-S** [robertfwallis/toontownsfunnyfarm-issue-tracker#6]

**Comment by Hitherepeople101** [comment]
Here is the code I've been getting when crashing from the building:
`Reading preferences.json...
TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
:12-26-2019 11:19:42 ToonBase: Default graphics pipe is wglGraphicsPipe (OpenGL).
:12-26-2019 11:19:43 ToonBase: Successfully opened window of type wglGraphicsWindow (OpenGL)
:12-26-2019 11:19:43 ShowBase: __dev__ == False
:12-26-2019 11:19:44 FunnyFarmStart: Starting the game.
:12-26-2019 11:19:44 FunnyFarmStart: Setting default GUI globals
:12-26-2019 11:19:44 FunnyFarmStart: Initializing AI Repository...
:12-26-2019 11:19:44 AIRepository: Creating managers...
:12-26-2019 11:19:44 FunnyFarmStart: Initializing Client Repository...
:12-26-2019 11:19:49 AIRepository: Preloading avatars...
:12-26-2019 11:19:50 AIRepository: Creating safe zones...
:12-26-2019 11:19:50 HoodAI: Creating objects... Funny Farm
:12-26-2019 11:19:55 HoodAI: Creating objects... Funny Farm, Rickety Road
:12-26-2019 11:19:56 AIRepository: Done.
:12-26-2019 11:20:05 Loader: starting bulk load of block 'main'
:12-26-2019 11:20:05 DataManager: ================
:12-26-2019 11:20:05 DataManager: Chose avatar id: 1000002
:12-26-2019 11:20:05 DataManager: Chose avatar name: Smoky
:12-26-2019 11:20:05 DataManager: ================
:12-26-2019 11:20:06 Loader: At end of block 'main', expected 1000, loaded 1, duration=1.0850615999999995
:12-26-2019 11:20:06 Loader: starting bulk load of block 'hood'
:12-26-2019 11:20:06 Loader: At end of block 'hood', expected 6, loaded 3, duration=0.7861052999999991
:12-26-2019 11:20:23 Actor(warning): no part named head-front*!
:12-26-2019 11:22:56 Actor(warning): no part named head-front*!
:12-26-2019 11:23:28 Loader: starting bulk load of block 'street'
:12-26-2019 11:23:29 Loader: At end of block 'street', expected 40, loaded 6, duration=1.4648085999999978
Traceback (most recent call last):
  File "<frozen direct.showbase.EventManager>", line 49, in eventLoopTask
  File "<frozen direct.showbase.EventManager>", line 43, in doEvents
  File "<frozen direct.showbase.EventManager>", line 99, in processEvent
  File "<frozen direct.showbase.Messenger>", line 336, in send
  File "<frozen direct.showbase.Messenger>", line 421, in __dispatch
  File "<frozen direct.gui.DirectButton>", line 107, in commandFunc
  File "<frozen direct.gui.DirectDialog>", line 181, in <lambda>
  File "<frozen direct.gui.DirectDialog>", line 344, in buttonCommand
  File "<frozen toontown.building.Elevator>", line 164, in handleDialog
  File "<frozen toontown.building.Elevator>", line 135, in board
NameError: name 'apply' is not defined
:12-26-2019 11:24:01 ToonBase(warning): Handling Python exception.
:12-26-2019 11:24:01 ToonBase: Exception exit.

Traceback (most recent call last):
  File "<frozen otp.otpbase.OTPBase>", line 243, in run
  File "<frozen direct.task.Task>", line 534, in run
  File "<frozen direct.task.Task>", line 488, in step
  File "<frozen direct.showbase.EventManager>", line 49, in eventLoopTask
  File "<frozen direct.showbase.EventManager>", line 43, in doEvents
  File "<frozen direct.showbase.EventManager>", line 99, in processEvent
  File "<frozen direct.showbase.Messenger>", line 336, in send
  File "<frozen direct.showbase.Messenger>", line 421, in __dispatch
  File "<frozen direct.gui.DirectButton>", line 107, in commandFunc
  File "<frozen direct.gui.DirectDialog>", line 181, in <lambda>
  File "<frozen direct.gui.DirectDialog>", line 344, in buttonCommand
  File "<frozen toontown.building.Elevator>", line 164, in handleDialog
  File "<frozen toontown.building.Elevator>", line 135, in board
NameError: name 'apply' is not defined
`

**Comment by NathanX-S** [comment]
Fixed in a93ce3e806bf1d5fc42729a666dfc96830110d25

**Comment by NathanX-S** [comment]
Fixed for 1.4.1
